rocketmq:
  # nameserver地址
  name-server: 192.168.66.102:9876
  producer:
    # 生产组
    group: my-group1
    # 发送消息超时时间
    send-message-timeout: 300000
demo:
  rocketmq:
    topic: test
    consumer: user_consumer


server:
  port: 9988